name: Publish package
on:
    release:
        types: [ created ]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            -   name: Dump GitHub context
                env:
                    GITHUB_CONTEXT: ${{ toJson(github) }}
                run: echo "$GITHUB_CONTEXT"
            -   uses: actions/checkout@v3
            -   uses: actions/setup-node@v3
                with:
                    node-version: 18
                    registry-url: 'https://registry.npmjs.org'
            -   run: echo ${{ toJSON(github) }}
            -   run: npm ci
            -   run: npm version ${{ github.event.workflow_run.head_branch }} --workspaces
            -   run: npm publish --access public --workspaces
            -   run: git config --global user.email bot@easy-breezy.com
            -   run: git config --global user.name bot
            -   run: git push
            -   run: git push --tags
                env:
                    NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
